// app/layout.jsx
import localFont from 'next/font/local'
import Link from 'next/link'
import ModeToggle from './components/modetoggle'
import { Inter } from 'next/font/google'
import HeaderNav from './components/HeaderNav'
import Contact from './components/Contact'
import { ScrollTimelineProvider } from './context/TimelineContext'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const rodinPro = localFont({
  src: [
    { path: '../public/fonts/FOT-RodinProN-L.otf', weight: '300', style: 'normal' },
    { path: '../public/fonts/FOT-RodinProN-M.otf', weight: '400', style: 'normal' },
    { path: '../public/fonts/FOT-RodinProN-DB.otf', weight: '500', style: 'normal' },
    { path: '../public/fonts/FOT-RodinProN-B.otf', weight: '600', style: 'normal' },
    { path: '../public/fonts/FOT-RodinProN-EB.otf', weight: '700', style: 'normal' },
    { path: '../public/fonts/FOT-RodinProN-UB.otf', weight: '800', style: 'normal' },
  ],
  variable: '--font-rodin-pro',
  display: 'swap',
})

const rodin = localFont({
  src: [
    { path: '../public/fonts/Rodin-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../public/fonts/Rodin-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../public/fonts/Rodin-Italic.ttf', weight: '400', style: 'italic' },
    { path: '../public/fonts/Rodin-BoldItalic.ttf', weight: '700', style: 'italic' },
  ],
  variable: '--font-rodin',
  display: 'swap',
})

const BarcodeTFB = localFont({
  src: '../public/fonts/BARCODE TFB.ttf',
  variable: '--barcode-tfb',
  display: 'swap',
})

const alongSansS2 = localFont({
  src: '../public/fonts/AlongSanss2-Regular.otf',
  variable: '--along-sans',
  display: 'swap',
})

// In JS, don't type `metadata`
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta property="og:type" content="website" />
      </head>
      <body
        className={`${inter.className} ${rodinPro.className} ${rodin.variable} ${alongSansS2.variable} ${BarcodeTFB.variable} antialiased`}
      >
      <ScrollTimelineProvider>
        <HeaderNav></HeaderNav>

        <main>{children}</main>
    
        <Contact />
        </ScrollTimelineProvider>
      </body>
    </html>
  )
}
